# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'dockertestimage:$(build.buildId)'
  dockerId: nsdockertest  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  
steps:
- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
    docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
  env:
    pswd: 'm@rk1247'        # Define dockerPassword in the Variables tab of this pipeline in Pipelines page of web interface